# v2 syntax
version: '2'

services:

  # PHP (with Caddy)
  app:
    image: ambientum/php:7.0-caddy
    container_name: PHPHttpRequest
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
